ALTER TABLE public.social_platforms
    ADD COLUMN IF NOT EXISTS icon_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS background_color_hex VARCHAR(9),
    ADD COLUMN IF NOT EXISTS icon_tint_color_hex VARCHAR(9),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

UPDATE public.social_platforms SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL;

ALTER TABLE public.social_platforms
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT NOW(),
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT NOW();

-- Align seed data with what the Android client actually sends today (root cause of the platform-code drift bugs:
-- Android's "GitHub" option had no matching backend row/enum constant, and this table's "Snapchat" row has no
-- Android UI/icon support).
UPDATE public.social_platforms SET background_color_hex = '#FDF2F8', icon_tint_color_hex = '#DB2777', sort_order = 1 WHERE code = 'INSTAGRAM';
UPDATE public.social_platforms SET background_color_hex = '#F1F5F9', icon_tint_color_hex = '#0F172A', sort_order = 2 WHERE code = 'X';
UPDATE public.social_platforms SET background_color_hex = '#EFF6FF', icon_tint_color_hex = '#2563EB', sort_order = 3 WHERE code = 'FACEBOOK';
UPDATE public.social_platforms SET background_color_hex = '#EFF6FF', icon_tint_color_hex = '#2563EB', sort_order = 4 WHERE code = 'LINKEDIN';
UPDATE public.social_platforms SET active = FALSE WHERE code = 'SNAPCHAT';

INSERT INTO public.social_platforms (id, code, label, sort_order, active, background_color_hex, icon_tint_color_hex)
SELECT 6, 'GITHUB', 'GitHub', 5, TRUE, '#F1F5F9', '#0F172A'
WHERE NOT EXISTS (SELECT 1 FROM public.social_platforms WHERE code = 'GITHUB');

-- Convert to an identity column so the new admin "add platform" endpoint can insert rows without manual id assignment.
ALTER TABLE public.social_platforms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.social_platforms', 'id'), (SELECT MAX(id) FROM public.social_platforms));
