-- Premium catalog: admin-managed pricing plans + feature bullets (backend-driven PremiumInfoScreen).
-- Two tables, identity PKs (so the admin "add feature" endpoint can insert without manual ids),
-- seeded idempotently with the values previously hardcoded in the Android client.

CREATE TABLE IF NOT EXISTS public.premium_plans (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period           VARCHAR(16)  NOT NULL UNIQUE,          -- MONTHLY | YEARLY
    amount           NUMERIC(10, 2) NOT NULL,
    currency         CHAR(3)      NOT NULL DEFAULT 'TRY',
    discount_percent INTEGER          NULL,                 -- e.g. 32 on the yearly plan
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.premium_features (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon_key     VARCHAR(48)  NOT NULL DEFAULT 'check',
    title_tr     VARCHAR(160) NOT NULL,
    title_en     VARCHAR(160) NOT NULL,
    subtitle_tr  VARCHAR(300)     NULL,
    subtitle_en  VARCHAR(300)     NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Seed plans (previous hardcoded ₺49/mo, ₺399/yr, 32% off on yearly).
INSERT INTO public.premium_plans (period, amount, currency, discount_percent, sort_order, active)
SELECT 'MONTHLY', 49.00, 'TRY', NULL, 1, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_plans WHERE period = 'MONTHLY');

INSERT INTO public.premium_plans (period, amount, currency, discount_percent, sort_order, active)
SELECT 'YEARLY', 399.00, 'TRY', 32, 2, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_plans WHERE period = 'YEARLY');

-- Seed the 6 feature bullets (bilingual, from the client's values-tr / values-en).
INSERT INTO public.premium_features (icon_key, title_tr, title_en, sort_order, active)
SELECT 'reviews', 'Sınırsız plaka değerlendirmesi', 'Unlimited plate reviews', 1, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_features WHERE sort_order = 1);

INSERT INTO public.premium_features (icon_key, title_tr, title_en, sort_order, active)
SELECT 'adfree', 'Reklamsız deneyim', 'Ad-free experience', 2, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_features WHERE sort_order = 2);

INSERT INTO public.premium_features (icon_key, title_tr, title_en, sort_order, active)
SELECT 'search', 'Gelişmiş arama filtreleri', 'Advanced search filters', 3, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_features WHERE sort_order = 3);

INSERT INTO public.premium_features (icon_key, title_tr, title_en, sort_order, active)
SELECT 'badge', 'Öne çıkan profil rozeti', 'Featured profile badge', 4, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_features WHERE sort_order = 4);

INSERT INTO public.premium_features (icon_key, title_tr, title_en, sort_order, active)
SELECT 'alerts', 'Takip edilen plakalar için anlık uyarı', 'Instant alerts for followed plates', 5, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_features WHERE sort_order = 5);

INSERT INTO public.premium_features (icon_key, title_tr, title_en, sort_order, active)
SELECT 'stats', 'Detaylı profil istatistikleri', 'Detailed profile statistics', 6, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.premium_features WHERE sort_order = 6);
