-- Theme catalog: admin-managed accent color palette + grid size (backend-driven ThemeColor screen),
-- plus per-user appearance (theme mode + selected accent) written through from the client.

CREATE TABLE IF NOT EXISTS public.accent_colors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hex        CHAR(7)   NOT NULL UNIQUE,        -- #RRGGBB
    sort_order INTEGER   NOT NULL DEFAULT 0,
    active     BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Single-row config for the grid column count on the accent-color picker.
CREATE TABLE IF NOT EXISTS public.theme_config (
    id         BIGINT PRIMARY KEY,
    grid_size  INTEGER   NOT NULL DEFAULT 4,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO public.theme_config (id, grid_size)
SELECT 1, 4 WHERE NOT EXISTS (SELECT 1 FROM public.theme_config WHERE id = 1);

-- Seed the 8 colors the Android client currently ships (ThemeColorUiState.AccentColors).
INSERT INTO public.accent_colors (hex, sort_order, active)
SELECT v.hex, v.sort_order, TRUE
FROM (VALUES
    ('#06B6D4', 1),
    ('#2563EB', 2),
    ('#7C3AED', 3),
    ('#DB2777', 4),
    ('#E11D48', 5),
    ('#EA580C', 6),
    ('#16A34A', 7),
    ('#0F766E', 8)
) AS v(hex, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.accent_colors ac WHERE ac.hex = v.hex);

-- Per-user appearance (write-through from the client; backend "knows" the user's choice).
ALTER TABLE public.user_settings
    ADD COLUMN IF NOT EXISTS theme_mode VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS accent_hex CHAR(7) NULL;
