-- Create premium feature translations table
CREATE TABLE IF NOT EXISTS public.premium_feature_translations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premium_feature_id BIGINT       NOT NULL REFERENCES public.premium_features(id) ON DELETE CASCADE,
    locale             VARCHAR(5)   NOT NULL,
    title              VARCHAR(160) NOT NULL,
    subtitle           VARCHAR(300) NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE(premium_feature_id, locale)
);

CREATE INDEX idx_premium_feature_translations_locale ON public.premium_feature_translations(locale);

-- Migrate existing data from premium_features to premium_feature_translations
INSERT INTO public.premium_feature_translations (premium_feature_id, locale, title, subtitle)
SELECT id, 'tr', title_tr, subtitle_tr FROM public.premium_features;

INSERT INTO public.premium_feature_translations (premium_feature_id, locale, title, subtitle)
SELECT id, 'en', title_en, subtitle_en FROM public.premium_features;

-- Drop old localized columns from premium_features
ALTER TABLE public.premium_features
    DROP COLUMN title_tr,
    DROP COLUMN title_en,
    DROP COLUMN subtitle_tr,
    DROP COLUMN subtitle_en;

-- Create premium plan translations table
CREATE TABLE IF NOT EXISTS public.premium_plan_translations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premium_plan_id BIGINT       NOT NULL REFERENCES public.premium_plans(id) ON DELETE CASCADE,
    locale          VARCHAR(5)   NOT NULL,
    title           VARCHAR(160) NOT NULL,
    description     VARCHAR(500) NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE(premium_plan_id, locale)
);

CREATE INDEX idx_premium_plan_translations_locale ON public.premium_plan_translations(locale);
