-- Create social platform translations table
CREATE TABLE IF NOT EXISTS public.social_platform_translations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_platform_id BIGINT       NOT NULL REFERENCES public.social_platforms(id) ON DELETE CASCADE,
    locale             VARCHAR(5)   NOT NULL,
    label              VARCHAR(128) NOT NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE(social_platform_id, locale)
);

CREATE INDEX idx_social_platform_translations_locale ON public.social_platform_translations(locale);

-- Migrate existing data from social_platforms to social_platform_translations (fallback to English as primary, and copy for Turkish too)
INSERT INTO public.social_platform_translations (social_platform_id, locale, label)
SELECT id, 'en', label FROM public.social_platforms;

INSERT INTO public.social_platform_translations (social_platform_id, locale, label)
SELECT id, 'tr', label FROM public.social_platforms;

-- Drop old localized column from social_platforms
ALTER TABLE public.social_platforms
    DROP COLUMN label;
