-- V34: comment_report_reasons becomes an admin-managed catalog.
-- Restores the label column (dropped in V32), adds requires_description + timestamps,
-- and converts id to identity so admin-created rows can be inserted without explicit ids.

ALTER TABLE public.comment_report_reasons ADD COLUMN IF NOT EXISTS label VARCHAR(128);

UPDATE public.comment_report_reasons
SET label = CASE code
    WHEN 'HATE_SPEECH' THEN 'Hate Speech'
    WHEN 'INSULT' THEN 'Insult'
    WHEN 'FALSE_INFORMATION' THEN 'False Information'
    WHEN 'PERSONAL_DATA' THEN 'Personal Data'
    WHEN 'THREAT' THEN 'Threat'
    WHEN 'SPAM' THEN 'Spam'
    WHEN 'OTHER' THEN 'Other'
    ELSE code
END
WHERE label IS NULL;

ALTER TABLE public.comment_report_reasons ALTER COLUMN label SET NOT NULL;

ALTER TABLE public.comment_report_reasons ADD COLUMN IF NOT EXISTS requires_description BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE public.comment_report_reasons SET requires_description = TRUE WHERE code = 'OTHER';

ALTER TABLE public.comment_report_reasons ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE public.comment_report_reasons ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

-- Rows so far were inserted with explicit ids (V11); switch to identity for admin inserts.
ALTER TABLE public.comment_report_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('public.comment_report_reasons', 'id'),
    COALESCE((SELECT MAX(id) FROM public.comment_report_reasons), 1)
);

CREATE INDEX IF NOT EXISTS idx_comment_report_reasons_active_sort
    ON public.comment_report_reasons (active, sort_order);
