-- V39: plate_removal_request_reasons becomes an admin-managed catalog, mirroring V34's fix for
-- comment_report_reasons (the same class of gap: PlateRemovalRequestReason was already coded as an
-- entity expecting label/requires_description/timestamps/identity-id, but the table was never migrated
-- to match — label was dropped in V32 and never restored, and id was never converted to identity).

ALTER TABLE public.plate_removal_request_reasons ADD COLUMN IF NOT EXISTS label VARCHAR(128);

UPDATE public.plate_removal_request_reasons
SET label = CASE code
    WHEN 'PLATE_BELONGS_TO_ME' THEN 'Plate Belongs To Me'
    WHEN 'FALSE_INFORMATION' THEN 'False Information'
    WHEN 'PRIVACY_REQUEST' THEN 'Privacy Request'
    WHEN 'HARASSMENT' THEN 'Harassment'
    WHEN 'LEGAL_REQUEST' THEN 'Legal Request'
    WHEN 'OTHER' THEN 'Other'
    ELSE code
END
WHERE label IS NULL;

ALTER TABLE public.plate_removal_request_reasons ALTER COLUMN label SET NOT NULL;

ALTER TABLE public.plate_removal_request_reasons ADD COLUMN IF NOT EXISTS requires_description BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE public.plate_removal_request_reasons SET requires_description = TRUE WHERE code = 'OTHER';

ALTER TABLE public.plate_removal_request_reasons ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE public.plate_removal_request_reasons ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

-- Rows so far were inserted with explicit ids (V11); switch to identity for admin inserts.
ALTER TABLE public.plate_removal_request_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('public.plate_removal_request_reasons', 'id'),
    COALESCE((SELECT MAX(id) FROM public.plate_removal_request_reasons), 1)
);

CREATE INDEX IF NOT EXISTS idx_plate_removal_request_reasons_active_sort
    ON public.plate_removal_request_reasons (active, sort_order);
